package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}
	
	public String getId() {
		return getStr("id");
	}

	public M setCode(String code) {
		set("code", code);
		return (M)this;
	}
	
	public String getCode() {
		return getStr("code");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setPinyin(String pinyin) {
		set("pinyin", pinyin);
		return (M)this;
	}
	
	public String getPinyin() {
		return getStr("pinyin");
	}

	public M setLinkman(String linkman) {
		set("linkman", linkman);
		return (M)this;
	}
	
	public String getLinkman() {
		return getStr("linkman");
	}

	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public M setLocation(String location) {
		set("location", location);
		return (M)this;
	}
	
	public String getLocation() {
		return getStr("location");
	}

	public M setEnable(String enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public String getEnable() {
		return getStr("enable");
	}

	public M setCreateUserId(String createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public String getCreateUserId() {
		return getStr("createUserId");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

	public M setModifyUserId(String modifyUserId) {
		set("modifyUserId", modifyUserId);
		return (M)this;
	}
	
	public String getModifyUserId() {
		return getStr("modifyUserId");
	}

	public M setModifyDate(String modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public String getModifyDate() {
		return getStr("modifyDate");
	}

}
