package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}
	
	public String getId() {
		return getStr("id");
	}

	public M setDeptId(String deptId) {
		set("deptId", deptId);
		return (M)this;
	}
	
	public String getDeptId() {
		return getStr("deptId");
	}

	public M setCode(String code) {
		set("code", code);
		return (M)this;
	}
	
	public String getCode() {
		return getStr("code");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setUsername(String username) {
		set("username", username);
		return (M)this;
	}
	
	public String getUsername() {
		return getStr("username");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}
	
	public String getPassword() {
		return getStr("password");
	}

	public M setEnable(String enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public String getEnable() {
		return getStr("enable");
	}

	public M setCreateUserId(String createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public String getCreateUserId() {
		return getStr("createUserId");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

	public M setModifyUserId(String modifyUserId) {
		set("modifyUserId", modifyUserId);
		return (M)this;
	}
	
	public String getModifyUserId() {
		return getStr("modifyUserId");
	}

	public M setModifyDate(String modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public String getModifyDate() {
		return getStr("modifyDate");
	}

	public M setEpc(String epc) {
		set("epc", epc);
		return (M)this;
	}
	
	public String getEpc() {
		return getStr("epc");
	}

	public M setRoles(String roles) {
		set("roles", roles);
		return (M)this;
	}

	public String getRoles() {
		return getStr("roles");
	}

}
