package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLocation<M extends BaseLocation<M>> extends Model<M> implements IBean {
    public M setId(Integer id) {
        set("id", id);
        return (M) this;
    }

    public Integer getId() {
        return getInt("id");
    }

    public M setEpc(String epc) {
        set("epc", epc);
        return (M) this;
    }

    public String getEpc() {
        return getStr("epc");
    }

    public M setCabinet(String cabinet) {
        set("cabinet", cabinet);
        return (M) this;
    }

    public String getCabinet() {
        return getStr("cabinet");
    }
}
