package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLogSpd<M extends BaseLogSpd<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}
	
	public String getId() {
		return getStr("id");
	}

	public M setModule(String module) {
		set("module", module);
		return (M)this;
	}

	public String getModule() {
		return getStr("module");
	}

	public M setMethod(String method) {
		set("method", method);
		return (M)this;
	}

	public String getMethod() {
		return getStr("method");
	}

	public M setUrl(String url) {
		set("url", url);
		return (M)this;
	}
	
	public String getUrl() {
		return getStr("url");
	}

	public M setParameter(String parameter) {
		set("parameter", parameter);
		return (M)this;
	}
	
	public String getParameter() {
		return getStr("parameter");
	}

	public M setErrorMessage(String errorMessage) {
		set("errorMessage", errorMessage);
		return (M)this;
	}
	
	public String getErrorMessage() {
		return getStr("errorMessage");
	}

	public M setResult(String result) {
		set("result", result);
		return (M)this;
	}

	public String getResult() {
		return getStr("result");
	}

	public M setState(String state) {
		set("state", state);
		return (M)this;
	}
	
	public String getState() {
		return getStr("state");
	}

	public M setExecuteTime(Integer executeTime) {
		set("executeTime", executeTime);
		return (M)this;
	}
	
	public Integer getExecuteTime() {
		return getInt("executeTime");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

}
