package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStockBase<M extends BaseStockBase<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}
	
	public String getId() {
		return getStr("id");
	}

	public M setGoodsId(String goodsId) {
		set("goodsId", goodsId);
		return (M)this;
	}
	
	public String getGoodsId() {
		return getStr("goodsId");
	}

	public M setDeptId(String deptId) {
		set("deptId", deptId);
		return (M)this;
	}
	
	public String getDeptId() {
		return getStr("deptId");
	}

	public M setMax(Integer max) {
		set("max", max);
		return (M)this;
	}
	
	public Integer getMax() {
		return getInt("max");
	}

	public M setMin(Integer min) {
		set("min", min);
		return (M)this;
	}
	
	public Integer getMin() {
		return getInt("min");
	}

	public M setCreateUserId(String createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public String getCreateUserId() {
		return getStr("createUserId");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

	public M setModifyUserId(String modifyUserId) {
		set("modifyUserId", modifyUserId);
		return (M)this;
	}
	
	public String getModifyUserId() {
		return getStr("modifyUserId");
	}

	public M setModifyDate(String modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public String getModifyDate() {
		return getStr("modifyDate");
	}

}
