package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecordInventoryDifference<M extends BaseRecordInventoryDifference<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}
	
	public String getId() {
		return getStr("id");
	}

	public M setDeptId(String deptId) {
		set("deptId", deptId);
		return (M)this;
	}
	
	public String getDeptId() {
		return getStr("deptId");
	}

	public M setCabinetId(String cabinetId) {
		set("cabinetId", cabinetId);
		return (M)this;
	}
	
	public String getCabinetId() {
		return getStr("cabinetId");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

	public M setStockActual(Integer stockActual) {
		set("stockActual", stockActual);
		return (M)this;
	}
	
	public Integer getStockActual() {
		return getInt("stockActual");
	}

	public M setStockTheory(Integer stockTheory) {
		set("stockTheory", stockTheory);
		return (M)this;
	}
	
	public Integer getStockTheory() {
		return getInt("stockTheory");
	}

	public M setStockMore(Integer stockMore) {
		set("stockMore", stockMore);
		return (M)this;
	}
	
	public Integer getStockMore() {
		return getInt("stockMore");
	}

	public M setStockLess(Integer stockLess) {
		set("stockLess", stockLess);
		return (M)this;
	}
	
	public Integer getStockLess() {
		return getInt("stockLess");
	}

	public M setCreateUserId(String createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public String getCreateUserId() {
		return getStr("createUserId");
	}

}
