package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePrinter<M extends BasePrinter<M>> extends Model<M> implements IBean {

    public M setId(Integer id) {
        set("id", id);
        return (M) this;
    }

    public Integer getId() {
        return getInt("id");
    }

    public M setName(String name) {
        set("name", name);
        return (M) this;
    }

    public String getName() {
        return getStr("name");
    }

    public M setIp(String ip) {
        set("ip", ip);
        return (M) this;
    }

    public String getIp() {
        return getStr("ip");
    }

    public M setPort(String port) {
        set("port", port);
        return (M) this;
    }

    public String getPort() {
        return getStr("port");
    }

}

