package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecordInoutException<M extends BaseRecordInoutException<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}
	
	public String getId() {
		return getStr("id");
	}

	public M setCabinetId(String cabinetId) {
		set("cabinetId", cabinetId);
		return (M)this;
	}
	
	public String getCabinetId() {
		return getStr("cabinetId");
	}

	public M setCreateUserId(String createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public String getCreateUserId() {
		return getStr("createUserId");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

	public M setExceptionDesc(String exceptionDesc) {
		set("exceptionDesc", exceptionDesc);
		return (M)this;
	}
	
	public String getExceptionDesc() {
		return getStr("exceptionDesc");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}

	public String getType() {
		return getStr("type");
	}

	public M setQuantity(int quantity) {
		set("quantity", quantity);
		return (M)this;
	}

	public Integer getQuantity() {
		return getInt("quantity");
	}

}
