package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStockTag<M extends BaseStockTag<M>> extends Model<M> implements IBean {

	public M setSpdCode(String spdCode) {
		set("spdCode", spdCode);
		return (M)this;
	}
	
	public String getSpdCode() {
		return getStr("spdCode");
	}

	public M setDeptId(String deptId) {
		set("deptId", deptId);
		return (M)this;
	}
	
	public String getDeptId() {
		return getStr("deptId");
	}

	public M setCabinetId(String cabinetId) {
		set("cabinetId", cabinetId);
		return (M)this;
	}
	
	public String getCabinetId() {
		return getStr("cabinetId");
	}

	public M setManufacturerId(String manufacturerId) {
		set("manufacturerId", manufacturerId);
		return (M)this;
	}
	
	public String getManufacturerId() {
		return getStr("manufacturerId");
	}

	public M setSupplierId(String supplierId) {
		set("supplierId", supplierId);
		return (M)this;
	}
	
	public String getSupplierId() {
		return getStr("supplierId");
	}

	public M setGoodsId(String goodsId) {
		set("goodsId", goodsId);
		return (M)this;
	}
	
	public String getGoodsId() {
		return getStr("goodsId");
	}

	public M setBatchNo(String batchNo) {
		set("batchNo", batchNo);
		return (M)this;
	}
	
	public String getBatchNo() {
		return getStr("batchNo");
	}

	public M setExpireDate(String expireDate) {
		set("expireDate", expireDate);
		return (M)this;
	}
	
	public String getExpireDate() {
		return getStr("expireDate");
	}

	public M setCreateUserId(String createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public String getCreateUserId() {
		return getStr("createUserId");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

}
