package com.tsj.domain.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}
	
	public String getId() {
		return getStr("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setCommonName(String commonName) {
		set("commonName", commonName);
		return (M)this;
	}
	
	public String getCommonName() {
		return getStr("commonName");
	}

	public M setTradeName(String tradeName) {
		set("tradeName", tradeName);
		return (M)this;
	}
	
	public String getTradeName() {
		return getStr("tradeName");
	}

	public M setCode(String code) {
		set("code", code);
		return (M)this;
	}
	
	public String getCode() {
		return getStr("code");
	}

	public M setSpec(String spec) {
		set("spec", spec);
		return (M)this;
	}
	
	public String getSpec() {
		return getStr("spec");
	}

	public M setPrice(Double price) {
		set("price", price);
		return (M)this;
	}
	
	public Double getPrice() {
		return getDouble("price");
	}

	public M setUnit(String unit) {
		set("unit", unit);
		return (M)this;
	}
	
	public String getUnit() {
		return getStr("unit");
	}

	public M setSupplierId(String supplierId) {
		set("supplierId", supplierId);
		return (M)this;
	}
	
	public String getSupplierId() {
		return getStr("supplierId");
	}

	public M setManufacturerId(String manufacturerId) {
		set("manufacturerId", manufacturerId);
		return (M)this;
	}
	
	public String getManufacturerId() {
		return getStr("manufacturerId");
	}

	public M setImplant(String implant) {
		set("implant", implant);
		return (M)this;
	}
	
	public String getImplant() {
		return getStr("implant");
	}

	public M setEnable(String enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public String getEnable() {
		return getStr("enable");
	}

	public M setCreateUserId(String createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public String getCreateUserId() {
		return getStr("createUserId");
	}

	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public String getCreateDate() {
		return getStr("createDate");
	}

	public M setModifyUserId(String modifyUserId) {
		set("modifyUserId", modifyUserId);
		return (M)this;
	}
	
	public String getModifyUserId() {
		return getStr("modifyUserId");
	}

	public M setModifyDate(String modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public String getModifyDate() {
		return getStr("modifyDate");
	}

}
