
package com.tsj.api.vanx.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SPDWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/spd/SPDWebService.asmx.wsdl")
public class SPDWebService
    extends Service
{

    private final static URL SPDWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SPDWEBSERVICE_EXCEPTION;
    private final static QName SPDWEBSERVICE_QNAME = new QName("http://tempuri.org/", "SPDWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/spd/SPDWebService.asmx.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPDWEBSERVICE_WSDL_LOCATION = url;
        SPDWEBSERVICE_EXCEPTION = e;
    }

    public SPDWebService() {
        super(__getWsdlLocation(), SPDWEBSERVICE_QNAME);
    }

    public SPDWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPDWEBSERVICE_QNAME, features);
    }

    public SPDWebService(URL wsdlLocation) {
        super(wsdlLocation, SPDWEBSERVICE_QNAME);
    }

    public SPDWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPDWEBSERVICE_QNAME, features);
    }

    public SPDWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SPDWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SPDWebServiceSoap
     */
    @WebEndpoint(name = "SPDWebServiceSoap")
    public SPDWebServiceSoap getSPDWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SPDWebServiceSoap"), SPDWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SPDWebServiceSoap
     */
    @WebEndpoint(name = "SPDWebServiceSoap")
    public SPDWebServiceSoap getSPDWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SPDWebServiceSoap"), SPDWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPDWEBSERVICE_EXCEPTION!= null) {
            throw SPDWEBSERVICE_EXCEPTION;
        }
        return SPDWEBSERVICE_WSDL_LOCATION;
    }

}
