
package com.tsj.api.vanx.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SPDWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SPDWebServiceSoap {


    /**
     * SPD���ݽ���
     * 
     * @param insData
     * @param orgCode
     * @param dataMethod
     * @param dataType
     * @param insDataCheck
     * @param dataNo
     * @param safeCode
     * @param userCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendRecv", action = "http://tempuri.org/SendRecv")
    @WebResult(name = "SendRecvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendRecv", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendRecv")
    @ResponseWrapper(localName = "SendRecvResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendRecvResponse")
    public String sendRecv(
        @WebParam(name = "userCode", targetNamespace = "http://tempuri.org/")
        String userCode,
        @WebParam(name = "safeCode", targetNamespace = "http://tempuri.org/")
        String safeCode,
        @WebParam(name = "orgCode", targetNamespace = "http://tempuri.org/")
        String orgCode,
        @WebParam(name = "dataNo", targetNamespace = "http://tempuri.org/")
        String dataNo,
        @WebParam(name = "dataMethod", targetNamespace = "http://tempuri.org/")
        String dataMethod,
        @WebParam(name = "dataType", targetNamespace = "http://tempuri.org/")
        String dataType,
        @WebParam(name = "insData", targetNamespace = "http://tempuri.org/")
        String insData,
        @WebParam(name = "insDataCheck", targetNamespace = "http://tempuri.org/")
        String insDataCheck);

    /**
     * SPD���ݿ����Ӳ���
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TestDatabaseConnection", action = "http://tempuri.org/TestDatabaseConnection")
    @WebResult(name = "TestDatabaseConnectionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TestDatabaseConnection", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TestDatabaseConnection")
    @ResponseWrapper(localName = "TestDatabaseConnectionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TestDatabaseConnectionResponse")
    public String testDatabaseConnection();

}
