package com.tsj.domain.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

    public static void mapping(ActiveRecordPlugin arp) {
        arp.addMapping("base_cabinet", "id", Cabinet.class);
        arp.addMapping("base_dept", "id", Dept.class);
        arp.addMapping("base_goods", "id", Goods.class);
        arp.addMapping("base_manufacturer", "id", Manufacturer.class);
        arp.addMapping("base_material", "spdCode", Material.class);
        arp.addMapping("base_supplier", "id", Supplier.class);
        arp.addMapping("base_user", "id", User.class);
        arp.addMapping("com_order", "id", Order.class);
        arp.addMapping("com_record_in", "id", RecordIn.class);
        arp.addMapping("com_record_inout_exception", "id", RecordInoutException.class);
        arp.addMapping("com_record_inventory", "id", RecordInventory.class);
        arp.addMapping("com_record_inventory_difference", "id", RecordInventoryDifference.class);
        arp.addMapping("com_record_inventory_new", "id", RecordInventoryNew.class);
        arp.addMapping("com_record_out", "id", RecordOut.class);
        arp.addMapping("com_stock_base", "id", StockBase.class);
        arp.addMapping("com_stock_tag", "spdCode", StockTag.class);
        arp.addMapping("com_tag", "spdCode", Tag.class);
        arp.addMapping("sys_config", "id", Config.class);
        arp.addMapping("sys_log_login", "id", LogLogin.class);
        arp.addMapping("sys_log_operate", "id", LogOperate.class);
        arp.addMapping("sys_log_spd", "id", LogSpd.class);
        arp.addMapping("sys_menu", "id", Menu.class);
        arp.addMapping("sys_user_finger", "id", UserFinger.class);
        arp.addMapping("com_print", "spdCode", Print.class);
        arp.addMapping("base_printer", "id", Printer.class);
        arp.addMapping("com_location", "id", Location.class);
    }
}

