package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseCabinet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cabinet extends BaseCabinet<Cabinet> {
	public static final Cabinet dao = new Cabinet().dao();
}
