package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Location extends BaseLocation<Location> {
    public static final Location dao = new Location().dao();
}
