package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseLogLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogLogin extends BaseLogLogin<LogLogin> {
	public static final LogLogin dao = new LogLogin().dao();
}
