package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseLogOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogOperate extends BaseLogOperate<LogOperate> {
	public static final LogOperate dao = new LogOperate().dao();
}
