package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseLogSpd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogSpd extends BaseLogSpd<LogSpd> {
	public static final LogSpd dao = new LogSpd().dao();
}
