package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseManufacturer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manufacturer extends BaseManufacturer<Manufacturer> {
	public static final Manufacturer dao = new Manufacturer().dao();
}
