package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Material extends BaseMaterial<Material> {
	public static final Material dao = new Material().dao();
}
