package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseMenu;

import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu().dao();

	/**
	 * 子菜单
	 */
	private List<Menu> children;

	public void setChildren(List<Menu> menuList) {
		this.children = menuList;
	}

	public List<Menu> getChildren() {
		return this.children;
	}

	@Override
	protected Map<String, Object> _getAttrs() {
		Map<String, Object> attrs = super._getAttrs();
		attrs.put("children", this.getChildren());
		return attrs;
	}
}
