package com.tsj.domain.model;


import com.tsj.domain.model.base.BasePrint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Print extends BasePrint<Print> {
    public static final Print dao = new Print().dao();
}

