package com.tsj.domain.model;

import com.tsj.domain.model.base.BasePrinter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Printer extends BasePrinter<Printer> {
    public static final Printer dao = new Printer().dao();
}

