package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseRecordInoutException;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordInoutException extends BaseRecordInoutException<RecordInoutException> {
	public static final RecordInoutException dao = new RecordInoutException().dao();
}
