package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseRecordIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordIn extends BaseRecordIn<RecordIn> {
	public static final RecordIn dao = new RecordIn().dao();
}
