package com.tsj.domain.model;


import com.tsj.domain.model.base.BaseRecordInventoryNew;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordInventoryNew extends BaseRecordInventoryNew<RecordInventoryNew> {
    public static final RecordInventoryNew dao = new RecordInventoryNew().dao();
}

