package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseRecordInventoryDifference;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordInventoryDifference extends BaseRecordInventoryDifference<RecordInventoryDifference> {
	public static final RecordInventoryDifference dao = new RecordInventoryDifference().dao();
}
