package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseRecordInventory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordInventory extends BaseRecordInventory<RecordInventory> {
	public static final RecordInventory dao = new RecordInventory().dao();
}
