package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseRecordOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordOut extends BaseRecordOut<RecordOut> {
	public static final RecordOut dao = new RecordOut().dao();
}
