package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseStockBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockBase extends BaseStockBase<StockBase> {
	public static final StockBase dao = new StockBase().dao();
}
