package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseStockTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockTag extends BaseStockTag<StockTag> {
	public static final StockTag dao = new StockTag().dao();
}
