package com.tsj.domain.model;

import com.tsj.domain.model.base.BaseUserFinger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFinger extends BaseUserFinger<UserFinger> {
	public static final UserFinger dao = new UserFinger().dao();
}
